import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export default function Home({ films }) {
  console.log('films', films);
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Star Wars</h1>

        <p className={styles.description}>Últimos filmes</p>

        <div className={styles.grid}>
          {films.map((film) => {
            return (
              <div key={film.id} className={styles.card}>
                <h6>id: {film.id}</h6>
                <h3>{film.title}</h3>
                <h4>Diretor: {film.director}</h4>
                <h6>
                  Data de lançamento:{' '}
                  {new Date(film.releaseDate).toLocaleDateString('pt-BR')}
                </h6>
                <h5>Produtores: {film.producers}</h5>
                <p>
                  <strong>Últimos acontecimentos:</strong> {film.openingCrawl}
                </p>
                <h6>
                  Atualizado:{' '}
                  {new Date(film.edited).toLocaleDateString('pt-BR')}
                </h6>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: ' https://swapi-graphql.netlify.app/.netlify/functions/index',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
    query Root {
      allFilms {
        films {
          id
          title
          director
          releaseDate
          producers
          openingCrawl
          edited
        }
      }
    }
    `,
  });
  console.log('data', data);
  return {
    props: {
      films: data.allFilms.films,
    },
  };
}
